# 03. Data 어떻게 표현하면 좋을까? 배열(array)과 표(table)
### [ 목차 ]
#### 1. Numpy
#### 2. 데이터의 행렬 변환
#### 3. Pandas
#### 4. EDA(Exploratory  Data  Analysis) : 데이터 탐색

## 1. Numpy

### 1) 주요 기능

In [5]:
import numpy as np

A = np.arange(5)
print(A)
print(A.shape, A.ndim, A.size)
print()

B = np.array([0,1,2,3,4])
print(B)
print(B.shape, B.ndim, B.size)
print()

C = np.arange(10).reshape(2,5)
print(C)
print(C.shape, C.ndim, C.size)
print()

[0 1 2 3 4]
(5,) 1 5

[0 1 2 3 4]
(5,) 1 5

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5) 2 10



In [8]:
# 단위행렬
A = np.eye(3)
print(A)
print()

B = np.zeros([2,3])
print(B)
print()

C = np.ones([3,3])
print(C)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [9]:
A = np.arange(9).reshape(3,3)

print(A)
print()

print(A*2)
print()

print(A+2)
print()

print(A + [1, 2, 3])
print()

print(A + [[1], [2], [3]])
print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]



In [21]:
A = np.arange(9).reshape(3,3)

print(A)
print()

print(A[0])
print()

print(A[0, :])
print()

print(A[:, 0])
print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]

[0 1 2]

[0 3 6]



In [24]:
# 의사 난수를 생성하는 예제입니다. 여러번 실행해 보세요.
rand = np.random.random()    # 0~1사이
print(rand)

rand = np.random.randint(0,10)    # 0~9 사이 정수
print(rand)

rand = np.random.choice([0,1,2,3,4,5,6,7,8,9])    # 리스트 중 하나
print(rand)

rand = np.random.permutation(10)    # 뒤섞어서
print(rand)

rand = np.random.permutation([0,1,2,3,4,5,6,7,8,9])
print(rand)


0.6127823968231292
8
3
[6 4 5 0 9 3 7 8 1 2]
[3 6 7 4 8 1 0 5 2 9]


In [28]:
A = np.arange(10).reshape(2,5)
print(A)
print(A.T)
print(np.transpose(A))
print()

B = np.arange(24).reshape(2,3,4)
print(B)
print(B.T)
print(np.transpose(B))
print()


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]



### 2) 통계 데이터

In [31]:
number = np.arange(1, 11)

print(number)
print(np.sum(number))    # 합
print(np.mean(number))    # 평균값
print(np.std(number))    # 표준편차
print(np.median(number))    # 중앙값

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
2.8722813232690143
5.5


## 2. 데이터의 행렬 변환

In [37]:
from PIL import Image, ImageColor
import os

img_path = os.getenv("HOME") + "/aiffel/data_represent/image/newyork.jpg"
img = Image.open(img_path)

print(img)
print(img.size)
print(img.format)
print(img.mode)
print()

img_arr = np.array(img)
print(img_arr)
print(img_arr.shape)
print()

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=212x300 at 0x7FCCCA97EFD0>
(212, 300)
JPEG
RGB

[[[133 180 250]
  [133 180 250]
  [133 180 250]
  ...
  [133 180 250]
  [133 180 250]
  [133 180 250]]

 [[133 180 250]
  [133 180 250]
  [133 180 250]
  ...
  [133 180 250]
  [133 180 250]
  [133 180 250]]

 [[133 180 250]
  [133 180 250]
  [133 180 250]
  ...
  [133 180 250]
  [133 180 250]
  [133 180 250]]

 ...

 [[164 199 255]
  [164 199 255]
  [164 199 255]
  ...
  [164 199 255]
  [164 199 255]
  [164 199 255]]

 [[164 199 255]
  [164 199 255]
  [164 199 255]
  ...
  [164 199 255]
  [164 199 255]
  [164 199 255]]

 [[164 199 255]
  [164 199 255]
  [164 199 255]
  ...
  [164 199 255]
  [164 199 255]
  [164 199 255]]]
(300, 212, 3)



In [44]:
img_path = os.getenv("HOME") + "/aiffel/data_represent/image/newyork.jpg"
img = Image.open(img_path)


cropped_img = img.crop((30, 30, 100, 100))    #  crop(left, up, rigth, down)
print(cropped_img)
print(cropped_img.size)
print(cropped_img.format)
print(cropped_img.mode)
print()

cropped_img_arr = np.array(cropped_img)
print(cropped_img_arr)
print(cropped_img_arr.shape)
print()

cropped_img_path = os.getenv("HOME") + "/aiffel/data_represent/image/croped_img.jpg"
cropped_img.save(cropped_img_path)


<PIL.Image.Image image mode=RGB size=70x70 at 0x7FCCC9CC0F90>
(70, 70)
None
RGB

[[[134 181 251]
  [134 181 251]
  [135 182 252]
  ...
  [136 183 253]
  [136 183 253]
  [136 183 253]]

 [[134 181 251]
  [134 181 251]
  [135 182 252]
  ...
  [136 183 253]
  [136 183 253]
  [136 183 253]]

 [[138 182 253]
  [138 182 253]
  [138 182 253]
  ...
  [138 182 253]
  [138 182 253]
  [138 182 253]]

 ...

 [[143 186 255]
  [143 186 255]
  [143 186 255]
  ...
  [ 17  60  53]
  [ 71 128 113]
  [ 55 112  95]]

 [[143 186 255]
  [143 186 255]
  [143 186 255]
  ...
  [ 34  76  72]
  [ 71 125 112]
  [ 39  96  81]]

 [[143 186 255]
  [143 186 255]
  [143 186 255]
  ...
  [ 38  83  80]
  [ 59 110 103]
  [ 22  76  63]]]
(70, 70, 3)



In [49]:
img_g = Image.open(img_path).convert("L")
print(img_g)
print(img_g.size)
print(img_g.format)
print(img_g.mode)
print()

img_g_arr = np.array(img_g)
print(img_g_arr)
print(img_g_arr.shape)
print()

<PIL.Image.Image image mode=L size=212x300 at 0x7FCCC9CDB610>
(212, 300)
None
L

[[174 174 174 ... 174 174 174]
 [174 174 174 ... 174 174 174]
 [174 174 174 ... 174 174 174]
 ...
 [195 195 195 ... 195 195 195]
 [195 195 195 ... 195 195 195]
 [195 195 195 ... 195 195 195]]
(300, 212)



## 3. Pandas

In [55]:
import pandas as pd

data = { 'Region' : ['Korea', 'America', 'Chaina', 'Canada', 'Italy'],
         'Sales' : [300, 200, 500, 150, 50],
         'Amount' : [90, 80, 100, 30, 10],
         'Employee' : [20, 10, 30, 5, 3] }

df = pd.DataFrame(data)
col = df.columns
index = df.index

print(col)
print(index)
df

Index(['Region', 'Sales', 'Amount', 'Employee'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


Region  Sales  Amount  Employee
0    Korea    300      90        20
1  America    200      80        10
2   Chaina    500     100        30
3   Canada    150      30         5
4    Italy     50      10         3

In [54]:
df.index = ['one', 'two', 'three', 'four', 'five']
df.columns = ['a', 'b', 'c', 'd']

df

a    b    c   d
one      Korea  300   90  20
two    America  200   80  10
three   Chaina  500  100  30
four    Canada  150   30   5
five     Italy   50   10   3

## 4. EDA (Exploratory Data  Analysis) : 데이터 탐색

In [56]:
csv_path = os.getenv("HOME") + "/aiffel/data_represent/data/covid19_italy_region.csv"
data = pd.read_csv(csv_path)

data

SNo                 Date Country  RegionCode     RegionName   Latitude  \
0      0  2020-02-24T18:00:00     ITA          13        Abruzzo  42.351222   
1      1  2020-02-24T18:00:00     ITA          17     Basilicata  40.639471   
2      2  2020-02-24T18:00:00     ITA           4   P.A. Bolzano  46.499335   
3      3  2020-02-24T18:00:00     ITA          18       Calabria  38.905976   
4      4  2020-02-24T18:00:00     ITA          15       Campania  40.839566   
..   ...                  ...     ...         ...            ...        ...   
793  793  2020-04-01T17:00:00     ITA           9        Toscana  43.769231   
794  794  2020-04-01T17:00:00     ITA           4    P.A. Trento  46.068935   
795  795  2020-04-01T17:00:00     ITA          10         Umbria  43.106758   
796  796  2020-04-01T17:00:00     ITA           2  Valle d'Aosta  45.737503   
797  797  2020-04-01T17:00:00     ITA           5         Veneto  45.434905   

     Longitude  HospitalizedPatients  IntensiveCarePatients  \
0    13.398438                     0                      0   
1    15.805148                     0                      0   
2    11.356624                     0                      0   
3    16.594402                     0                      0   
4    14.250850                     0                      0   
..         ...                   ...                    ...   
793  11.255889                  1120                    297   
794  11.121231                   345                     76   
795  12.388247                   173                     45   
796   7.320149                    85                     27   
797  12.338452                  1718                    350   

     TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   
..                         ...              ...                   ...   
793                       1417             3015                  4432   
794                        421             1062                  1483   
795                        218              646                   864   
796                        112              428                   540   
797                       2068             6156                  8224   

     NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
0                   0          0       0                   0               5  
1                   0          0       0                   0               0  
2                   0          0       0                   0               1  
3                   0          0       0                   0               1  
4                   0          0       0                   0              10  
..                ...        ...     ...                 ...             ...  
793               259        182     253                4867           36575  
794               124        214     173                1870            7675  
795                17        194      37                1095            9080  
796                 3         32      59                 631            1717  
797               470        902     499                9625          112746  

[798 rows x 17 columns]

In [57]:
data.head()

SNo                 Date Country  RegionCode    RegionName   Latitude  \
0    0  2020-02-24T18:00:00     ITA          13       Abruzzo  42.351222   
1    1  2020-02-24T18:00:00     ITA          17    Basilicata  40.639471   
2    2  2020-02-24T18:00:00     ITA           4  P.A. Bolzano  46.499335   
3    3  2020-02-24T18:00:00     ITA          18      Calabria  38.905976   
4    4  2020-02-24T18:00:00     ITA          15      Campania  40.839566   

   Longitude  HospitalizedPatients  IntensiveCarePatients  \
0  13.398438                     0                      0   
1  15.805148                     0                      0   
2  11.356624                     0                      0   
3  16.594402                     0                      0   
4  14.250850                     0                      0   

   TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
0                          0                0                     0   
1                          0                0                     0   
2                          0                0                     0   
3                          0                0                     0   
4                          0                0                     0   

   NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
0                 0          0       0                   0               5  
1                 0          0       0                   0               0  
2                 0          0       0                   0               1  
3                 0          0       0                   0               1  
4                 0          0       0                   0              10

In [58]:
data.tail()

SNo                 Date Country  RegionCode     RegionName   Latitude  \
793  793  2020-04-01T17:00:00     ITA           9        Toscana  43.769231   
794  794  2020-04-01T17:00:00     ITA           4    P.A. Trento  46.068935   
795  795  2020-04-01T17:00:00     ITA          10         Umbria  43.106758   
796  796  2020-04-01T17:00:00     ITA           2  Valle d'Aosta  45.737503   
797  797  2020-04-01T17:00:00     ITA           5         Veneto  45.434905   

     Longitude  HospitalizedPatients  IntensiveCarePatients  \
793  11.255889                  1120                    297   
794  11.121231                   345                     76   
795  12.388247                   173                     45   
796   7.320149                    85                     27   
797  12.338452                  1718                    350   

     TotalHospitalizedPatients  HomeConfinement  CurrentPositiveCases  \
793                       1417             3015                  4432   
794                        421             1062                  1483   
795                        218              646                   864   
796                        112              428                   540   
797                       2068             6156                  8224   

     NewPositiveCases  Recovered  Deaths  TotalPositiveCases  TestsPerformed  
793               259        182     253                4867           36575  
794               124        214     173                1870            7675  
795                17        194      37                1095            9080  
796                 3         32      59                 631            1717  
797               470        902     499                9625          112746

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   SNo                        798 non-null    int64  
 1   Date                       798 non-null    object 
 2   Country                    798 non-null    object 
 3   RegionCode                 798 non-null    int64  
 4   RegionName                 798 non-null    object 
 5   Latitude                   798 non-null    float64
 6   Longitude                  798 non-null    float64
 7   HospitalizedPatients       798 non-null    int64  
 8   IntensiveCarePatients      798 non-null    int64  
 9   TotalHospitalizedPatients  798 non-null    int64  
 10  HomeConfinement            798 non-null    int64  
 11  CurrentPositiveCases       798 non-null    int64  
 12  NewPositiveCases           798 non-null    int64  
 13  Recovered                  798 non-null    int64  

In [61]:
data.describe()

SNo  RegionCode    Latitude   Longitude  HospitalizedPatients  \
count  798.00000  798.000000  798.000000  798.000000            798.000000   
mean   398.50000   10.190476   43.046293   12.225955            533.058897   
std    230.50705    5.798698    2.490342    2.660615           1532.090841   
min      0.00000    1.000000   38.115697    7.320149              0.000000   
25%    199.25000    5.000000   41.125596   11.121231              5.000000   
50%    398.50000   10.000000   43.616760   12.388247             64.000000   
75%    597.75000   15.000000   45.434905   13.768136            325.750000   
max    797.00000   20.000000   46.499335   16.867367          11927.000000   

       IntensiveCarePatients  TotalHospitalizedPatients  HomeConfinement  \
count             798.000000                 798.000000       798.000000   
mean               82.596491                 615.655388       674.998747   
std               190.735985                1719.508711      1627.086600   
min                 0.000000                   0.000000         0.000000   
25%                 0.000000                   6.000000         8.000000   
50%                16.000000                  80.500000       109.000000   
75%                71.750000                 396.250000       552.750000   
max              1342.000000               13269.000000     12496.000000   

       CurrentPositiveCases  NewPositiveCases     Recovered       Deaths  \
count            798.000000        798.000000    798.000000   798.000000   
mean            1290.654135        138.553885    205.706767   162.677945   
std             3282.834715        327.616052   1060.433732   700.264327   
min                0.000000        -17.000000      0.000000     0.000000   
25%               14.250000          2.000000      0.000000     0.000000   
50%              205.000000         32.000000      3.000000     6.000000   
75%              998.750000        117.750000     34.000000    55.750000   
max            25765.000000       3251.000000  11415.000000  7593.000000   

       TotalPositiveCases  TestsPerformed  
count          798.000000      798.000000  
mean          1659.038847     7932.164160  
std           4945.629053    17067.087279  
min              0.000000        0.000000  
25%             14.250000      230.000000  
50%            210.500000     1610.000000  
75%           1110.750000     7493.000000  
max          44773.000000   121449.000000

In [63]:
data.isnull().sum()

SNo                          0
Date                         0
Country                      0
RegionCode                   0
RegionName                   0
Latitude                     0
Longitude                    0
HospitalizedPatients         0
IntensiveCarePatients        0
TotalHospitalizedPatients    0
HomeConfinement              0
CurrentPositiveCases         0
NewPositiveCases             0
Recovered                    0
Deaths                       0
TotalPositiveCases           0
TestsPerformed               0
dtype: int64

In [64]:
data['RegionName'].value_counts()

Campania                 38
Lazio                    38
Emilia-Romagna           38
Toscana                  38
Molise                   38
Valle d'Aosta            38
Marche                   38
Friuli Venezia Giulia    38
Piemonte                 38
Sardegna                 38
Basilicata               38
P.A. Trento              38
P.A. Bolzano             38
Liguria                  38
Puglia                   38
Sicilia                  38
Calabria                 38
Abruzzo                  38
Umbria                   38
Veneto                   38
Lombardia                38
Name: RegionName, dtype: int64

In [66]:
data.drop(['HospitalizedPatients',  'IntensiveCarePatients', 'TotalHospitalizedPatients','HomeConfinement']
          , axis=1
          , inplace=True)

data

SNo                 Date Country  RegionCode     RegionName   Latitude  \
0      0  2020-02-24T18:00:00     ITA          13        Abruzzo  42.351222   
1      1  2020-02-24T18:00:00     ITA          17     Basilicata  40.639471   
2      2  2020-02-24T18:00:00     ITA           4   P.A. Bolzano  46.499335   
3      3  2020-02-24T18:00:00     ITA          18       Calabria  38.905976   
4      4  2020-02-24T18:00:00     ITA          15       Campania  40.839566   
..   ...                  ...     ...         ...            ...        ...   
793  793  2020-04-01T17:00:00     ITA           9        Toscana  43.769231   
794  794  2020-04-01T17:00:00     ITA           4    P.A. Trento  46.068935   
795  795  2020-04-01T17:00:00     ITA          10         Umbria  43.106758   
796  796  2020-04-01T17:00:00     ITA           2  Valle d'Aosta  45.737503   
797  797  2020-04-01T17:00:00     ITA           5         Veneto  45.434905   

     Longitude  CurrentPositiveCases  NewPositiveCases  Recovered  Deaths  \
0    13.398438                     0                 0          0       0   
1    15.805148                     0                 0          0       0   
2    11.356624                     0                 0          0       0   
3    16.594402                     0                 0          0       0   
4    14.250850                     0                 0          0       0   
..         ...                   ...               ...        ...     ...   
793  11.255889                  4432               259        182     253   
794  11.121231                  1483               124        214     173   
795  12.388247                   864                17        194      37   
796   7.320149                   540                 3         32      59   
797  12.338452                  8224               470        902     499   

     TotalPositiveCases  TestsPerformed  
0                     0               5  
1                     0               0  
2                     0               1  
3                     0               1  
4                     0              10  
..                  ...             ...  
793                4867           36575  
794                1870            7675  
795                1095            9080  
796                 631            1717  
797                9625          112746  

[798 rows x 13 columns]